server:
  port: 8080
spring:
  application:
    name: iba
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sk_anyang_iba?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.sk.iba.module.*.entity
  configuration:
    map-underscore-to-camel-case: true #自动开启数据库下划线命名到 Java 驼峰命名的映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted #全局开启逻辑删除
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #不删除
knife4j:
  enable: true
iba:
  jwt:
    secret: sk-iba-intelligent-behavior-analysis-system-secret-2026
    expire-minutes: 1440
sk:
  file:
    algorithm-package-dir: D:/sk_iba/algorithm_packages